#!/bin/bash
#
# BASH script for quickly uploading new QSLs to:
# ARRL Logbook of the World, eQSL.cc and ClubLog.org
#
# Copyright 2020, Dave Slotter, W3DJS
#


CALLSIGN="<YOUR_CALLSIGN>"

LOTW_LOCATION="<YOUR_LOTW_STATION_LOCATION_FOR_CALLSIGN>"

EQSL_USER="${CALLSIGN}"
EQSL_PSWD="<YOUR_EQSL.CC_PASSWORD>"

CLUBLOG_EMAIL="<YOUR_CLUBLOG_EMAIL>"
CLUBLOG_PSWD="<YOUR_CLUBLOG_PASSWORD"
CLUBLOG_API="<YOUR_CLUBLOG_API_KEY>"

#
# Read https://clublog.freshdesk.com/support/solutions/articles/54910-api-keys
# on how to get a ClubLog API Key
#

if [ ! -x /usr/bin/curl ]; then
  echo "CURL is required. Please install it."
  exit 1
fi

if [ ! -x /usr/bin/espeak ]; then
  echo "espeak is required. Please install it."
  exit 1
fi

if [ ! -x /usr/bin/notify-send ]; then
  echo "notify-send is required. Please install it."
  exit 1
fi

TMPFILE=$(mktemp /tmp/wsjtx_log_delta_.XXXXXX.ADIF)

trap 'rm ${TMPFILE}' SIGTERM

# Get current highwater mark
WSJTX_LOG_NEW_HIGHWATER=$(wc -l ${HOME}/.local/share/WSJT-X/wsjtx_log.adi | cut -d ' ' -f1 )

# Get prior highwater mark
WSJTX_LOG_HIGHWATER=$(cat ${HOME}/.wsjtx_log_old_highwater)

NEW_LOG_LINES=$(( ${WSJTX_LOG_NEW_HIGHWATER} - ${WSJTX_LOG_HIGHWATER} ))
if (( ${NEW_LOG_LINES} > 0 )); then
  tail -n ${NEW_LOG_LINES} ${HOME}/.local/share/WSJT-X/wsjtx_log.adi > ${TMPFILE}

  # Upload to eQSL.cc
  echo -e "\nUploading to eQSL..."
  curl -s -F "EQSL_USER=${EQSL_USER}" -F "EQSL_PSWD=${EQSL_PSWD}" -F "Filename=@${TMPFILE}" https://www.eQSL.cc/qslcard/ImportADIF.cfm

  # Upload to ClubLog
  echo -e "\n\nUploading to ClubLog..."
  curl -s -F "email=${CLUBLOG_EMAIL}" -F "password=${CLUBLOG_PSWD}" -F "callsign=${CALLSIGN}" -F "api=${CLUBLOG_API}" -F "file=@${TMPFILE}" https://clublog.org/putlogs.php

  echo -e "\n\nUploading to Logbook of the World..."
  /usr/local/bin/tqsl --quiet --batch --nodate --location="${LOTW_LOCATION}" --upload --batch ${TMPFILE}
  if (( $? == 0 )); then
    espeak -s 150 -v en-us "Logbook of the world upload of, ${NEW_LOG_LINES}, cue-soes successful.!" 2> /dev/null &
    notify-send -i /usr/share/pixmaps/trustedqsl.png -t 60000 "LotW upload of ${NEW_LOG_LINES} QSO(s) successful" &
    # Write out new highwater mark:
    echo ${WSJTX_LOG_NEW_HIGHWATER} > ${HOME}/.wsjtx_log_old_highwater
    rm "$TMPFILE"
  fi
  else
    espeak -s 150 -v en-us "Nothing to upload to Logbook of the world.!" 2> /dev/null &
    notify-send -i /usr/share/pixmaps/trustedqsl.png -t 60000 "Nothing to upload to LotW." &
fi

